name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Employee variant
        run: npm run build:employee

      - name: Build NAQA variant
        run: npm run build:naqa

      - name: Build Student variant
        run: npm run build:student

      - name: Prepare combined dist
        run: |
          mkdir combined_dist
          mkdir combined_dist/v2
          cp -r dist/employee combined_dist/v2/employee
          cp -r dist/naqa-notification combined_dist/v2/naqa-notification
          cp -r dist/student combined_dist/v2/student

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './combined_dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
